#!/bin/bash
#----------------------------------------------------
#SBATCH -J myjob    # Job name
#SBATCH -o myjob.o%j  #Name of stdout output file
#SBATCH -e myjob.e%j #Name of stderr error file
#SBATCH -p development # Queue (partition) name
#SBATCH -N 1 # Total # of nodes (still use 1 node)
#SBATCH -n 16 # Total # ask for 16 cores on a node
#SBATCH -t 00:05:00 # Run time (hh:mm:ss)
#SBATCH --mail-user=pkamasani@umassd.edu
#SBATCH --mail-type=all

python3 ./Project.py


